dist: xenial
services: docker
language: minimal

addons:
 apt:
  packages:
  - curl
  - jq

dependencies: &deps
- xorg-dev
- libvulkan-dev

env:
- secure: "bahiF0wYoFBZJXyIrBnoLM/4MUg4e5CY32haTNtS78dPbFBme9xS6lKtpkdMnfvmoWbtj2veAii0V+m2BvWkjHHUP/9k6WPWkzB2S7QwllnWjLadid9UAOE6AaFgwT2Dj15GILJnjtiwGPyZHdAsT/6Mnw+QifaYP4kIcMskyFlD7HNDvfKOZpcfGoDDH8UEy7HFkzHSDwy8XR6EKvavCqTdG5CS6DDinm/hDU81A1v1G49S4/LIAU3LgsxJKu1TOVtj1iILOFl9g/jC/yng9mFocWYGOa1gUw2lZkfWE7gETZGedTmI1eJyKmSdHxV8bt/DiZJM1Xd2KMcoFP1snpNNRdM+N/W1GCHNhinxov2wp/p/bcFwH/PZ2e+i1PGeLjCWIFEv6FYieIMQwBDc8jt0zZN3Iy/hZC502bechpovlCkqHpiEuZwmBq/uHKaLiXNvjXGbstczTe8rO5PO3+xJN9hXr+EF8UwaRLwf7odYON3p3mzQrOj1WHRGkdAG3tg7QP23Wf84pDPxhY8+72qWeQSe2pTjvtv19FC8p6QmixiII3wqjAfdPt5O3Wz5fRZ3uZvOZdftnu2/um1h4JSLMLm0IHGhst7uWiT343qZ2U9dW+Pcequvy4Xbgib1MFt1saNapj8mVGaEesTk9fqYQPwzyZ5e6UHBMvOcrtQ="

matrix:
 include:
 - env:
   - COMPILER=clang
   - CXX=clang++-8
   - CC=clang-8
   - CXXFLAGS=-stdlib=libc++
   - LDLIBS=-lc++
 - env:
   - COMPILER=gcc
   - CXX=g++-8
   - CC=gcc-8

script:
- docker import $(curl -sL -A bit2shift --oauth2-bearer "$TOKEN" "https://api.github.com/repos/bit2shift/docker-r3v-toolchain-$COMPILER/releases/latest" | jq -r ".assets[0].browser_download_url")
