language: cpp
dist: xenial

dependencies: &deps
- xorg-dev
- libvulkan-dev

matrix:
 include:
 - compiler: clang-8
   env: MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
   addons:
    apt:
     sources:
     - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
       key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
     packages:
     - clang-8
     - libc++-dev
     - *deps
 - compiler: gcc-8
   env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
   addons:
    apt:
     sources: ubuntu-toolchain-r-test
     packages:
     - g++-8
     - *deps

before_install: eval "${MATRIX_EVAL}"
script: make
