dist: xenial
services: docker
language: minimal

addons:
 apt:
  packages:
  - curl
  - jq

dependencies: &deps
- xorg-dev
- libvulkan-dev

env:
- secure: "lRenF3X9U6pcIiTL13zLLAWl2URdF5qhtUonK5QbP5Nj9qediS8MhvtYsNrCsZXdVghPnrexSv0Vi5ZqjrxVBIwlJSSeFKUg62/raV1ZdMk0aTAcGUHcBthSNf+CU6WKv3agX82eRc/+yfEhcM0fHoaUhI5zvFjYFbfmuAqQ+sshOQBIPKbk425zPd8IR1J8NgeJ1Bu5iFCdovcTlH9d2pC22ExMkm1nL+L1qHN/dCOyJ1gCVEoaH3XOAH/hADex4nPpvc/a+uxJ/rZl8rt+bZDOzb95qPSZ72XA2V7E2mFZ2wH/tA3g6cALpGoI8pGmQvwRhopmV+CqRO1GzA4Y8NU2y1LwCQ1zf8D4Z2MhvRP7v7UoMVRpilxCQ/+nWi7le9vGkhZkMu0G87+4Jg+aIVV/rLPdflpBMk7PadxMeyIQHM+907FHZ+HzQ4Zbx/V7BjpGCc28lTbxDaIO+BWkR+ToqAktngxKWPdr8GEdj+Ke1gl6pBlo5ekkuNpBymYbZtvgsuA1lpk4aY3CWtcYzKujvslPW+wAtdazCZs8mJNfOqquGyGoBrjdB4Z0/uDAMuhrcfLBN3dcohhtfhDTamOLGGMiM+uaTWeINCyan5LJB8PC65Qq/BeqR2AvsLHFP7mVo7wfN6pojgGrILeAA4nRTK98HVHl7/k2Ua7ugTY="
- secure: "MBxhjpq3WdoOpBpZv+pwj4EjHp8poiwzc3wu/I0SzR5CL2z/Ql3/YMlLrOPbY6ZAIIWw+QCdXBP+8Gk44USJwCHd2xWptcAt/huxvG8ptff5OzqgkRYgXelqy/38CRtcUdHub4s3KCBG/ksAEBQCTI/POMNvyKdHhaCtY2UhMGHpwsFP2QpvlUbcED6wTxTUI2CKuMPdtbYe7sZT/b6M9U5nt8GhQZPjTDXnFvghAtGaGrHPjzXjtwvSfNB2xCC41d0bA2ABRAs5EwpZ0zGOic3qyAvz2hjbwLlHhfCnGtoJwt2p3PE1UUtn2gib/PFrOIKdOvroHQfa626Sx2lMxHVKfdixXlrxBr/qyAlUWONSZkdl1jODSLQoun71fzq0NCQqQDTqRzm1fPZSNwzZYCz0pjKu0H4/9dU3AZCu/22qXmi8uBF0uUOt24f5tbCv4s7aPbiiDktDX8oCsqE78zVZuM3Q1N+0WeOlkngbOE6252hM9xzNHqfWRj8vWuVHpXbMYeEnA9+zRqI0Jp83YW7xPnk186qO1VzeZs6ZVuN7IzoVH5rBkUFCmthH5JWJLaFzPO1NtAExkWYWNNbfmO1J3tR91UAwxCOr13bEChT3g9HpIIj3E+Akkg2dMUvPR3TNCCuKGcgh853qo0KANlgvYeHR7Yw6l8eGqDtmg9M="

matrix:
 include:
 - env:
   - COMPILER=clang
   - CXX=clang++-8
   - CC=clang-8
   - CXXFLAGS=-stdlib=libc++
   - LDLIBS=-lc++
 - env:
   - COMPILER=gcc
   - CXX=g++-8
   - CC=gcc-8

script:
- echo "'$DERP'"
- curl -sL -A bit2shift --oauth2-bearer $TOKEN "https://api.github.com/repos/bit2shift/docker-r3v-toolchain-$COMPILER/releases/latest"
#- 'docker import $(curl -sL -H "User-Agent: bit2shift" -H "Authorization: token $TOKEN" "https://api.github.com/repos/bit2shift/docker-r3v-toolchain-$COMPILER/releases/latest" | jq -r ".assets[0].browser_download_url")'
