language: cpp

dist: xenial

matrix:
 include:
 - env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
   addons:
    apt:
     sources: ubuntu-toolchain-r-test
     packages:
     - g++-8
     - xorg-dev
     - libvulkan-dev

script: make
