dist: xenial
services: docker
language: minimal

addons:
 apt:
  packages:
  - curl
  - jq

dependencies: &deps
- xorg-dev
- libvulkan-dev

env:
- secure: "JODxuqjrAc9Kw7PF5BQD0bNnhdqDD1gwfWlEL8MGcantFxvoRj3+4Qxc/16vXicr2AgeOrIPqNytqhuLna0i1y6WdO/7eNByCw9swakUKVHRg9Uf0YdxcT7ij5Z8Yf+2B/cTi5svHqC/p05lhgW+nza9zVnzWoYdFLB9+Yx6SP0pRYPOtg0sF4Z3SsVOn2dkVr3h9CFJScKDYkjLX+D5imfofm8S8GVjcl1MQ1ab4scVLoD+RoeNY+37Nv1wUsUCaXo86hHaj93tP+KuOW0SF9FYrD76bMW6uH8rmWZrAiEphWr8DgSwArrXohPOxiFJnkt5N3VFx0GC76vg2bsNlm2YFjVLSN3k2LyAUD5bEEhRYx+3bEbm0u2o+NKeJDhNES7A2GbjKlCOJ9SRCoUi689XZsNsWOM2Bshe4OtBYB6KW1gkoH9DKFbAKboX0bxvyKtBDYjAp2zXsUIXjg24l+nX//c541Pq2CysdHLuzJLYXxqk4z2VcayHTp+HZGNDNCpn4r011VUvdK8aShQYSvc/k5FE2RT8nDfx6+5EEnVyE9yIUZ45Y+65dT+n9rXicmnysuOGzSSwG/w89CeveFumb35K2WI6x0tKYc0GEsCMzc2c4PwamwiKa+8epOpSYFxz/cGrF6e9sdAYbkZlziKj0KWoj1AqZv9EoobPM04="

matrix:
 include:
 - env:
   - COMPILER=clang
   - CXX=clang++-8
   - CC=clang-8
   - CXXFLAGS=-stdlib=libc++
   - LDLIBS=-lc++
 - env:
   - COMPILER=gcc
   - CXX=g++-8
   - CC=gcc-8

script:
- curl -IL -A bit2shift --oauth2-bearer "$TOKEN" "https://api.github.com/repos/bit2shift/docker-r3v-toolchain-$COMPILER/releases/latest"
- docker import $(curl -sL -A bit2shift --oauth2-bearer "$TOKEN" "https://api.github.com/repos/bit2shift/docker-r3v-toolchain-$COMPILER/releases/latest" | jq -r ".assets[0].browser_download_url")
