dist: xenial
services: docker
language: minimal

addons:
 apt:
  packages:
  - curl
  - jq

dependencies: &deps
- xorg-dev
- libvulkan-dev

env:
- secure: "F5Bj8QOqUXTWsBZvMFWlWfhS/yyW/gwWCTJwsh7p2ZJEBncAEjH0K6GvzudRLewl9fylqZ/ySitxMJMXyYKdyHIiH25VbtT6MHGKYL3cNhy9IYHNPSQlxVVUXg6Jc/m3NOpQTqQQn/zZj1NyDS0esPm9Q716HDLyxVE/ky2YTSUAZ3xgNyxnyuYoQ2fOBbOcEqy/5/t72rJR86u7Xfe4ysqqAA3FOU5NpdoiSyUGEoxeCJYoiaRtDgA8x4oigufiEzncoEVEMRxYwh4G79FzmEI1OVXLgCJz/RGCBv3/GiKhhgd8Ivynn+5ZP5S3hhw36pDnej77tsO1OcQ88/0iQDzepKUTxlhoB7j9qOvuGuz43eYVlw7Q24JNRlrGs/mePA3Q1OjDDp+LokfRWLJ9AFnOGSQ+0xQlKVUYq0SyRLa+VEPE3a27nIPt/mYcKSUY8eg2tmhhGgDcXc6fCQNsi0w0i9uSvbgyDwn124+MfQs3qrEFv804lT3tFLDxgJKWiDfV5p3oEGUTffYYp9pG/VyG6Tk4jRHbE0Fj1CMg4p+CRc2Cyvzt6dYDYYpCArSSTMiv++VvvsTAGGyvWpDcTmk3V/Wu9QgUN07Va/RWTIVbLnyoQSqPNfD5ihWmQDDBAwE3ZQ49AvAQQQ0ag/Q6d1/l2/nVnG+VcPLqq4kYCKw="

matrix:
 include:
 - env:
   - COMPILER=clang
   - CXX=clang++-8
   - CC=clang-8
   - CXXFLAGS=-stdlib=libc++
   - LDLIBS=-lc++
 - env:
   - COMPILER=gcc
   - CXX=g++-8
   - CC=gcc-8

script:
- curl -IL -A bit2shift --oauth2-bearer "$TOKEN" "https://api.github.com/repos/bit2shift/docker-r3v-toolchain-$COMPILER/releases/latest"
- docker import $(curl -sL -A bit2shift --oauth2-bearer "$TOKEN" "https://api.github.com/repos/bit2shift/docker-r3v-toolchain-$COMPILER/releases/latest" | jq -r ".assets[0].browser_download_url")
