dist: xenial
services: docker
language: minimal

addons:
 apt:
  packages:
  - curl
  - jq

dependencies: &deps
- xorg-dev
- libvulkan-dev

env:
- secure: "NKLlSVmxck4AU2fmpv+6LhyE70Rm6UENacrBKtnoK/cOec0CnqnC3yX16e2P7AfF/5RDpFrAjQEtfASWQlKHh2llJZYTX5v1Far4wQn38llrMpdwCzRPBiNjMHewcxKygSFoFAwOHWm6yP8TTNvSagMp56/HsEG2YGV7KDW4GRM7PVzMcwtF+O+mYiY5KyJ5yKI9Pm1SvQfz8ptwEM9QLC5dgqGnz+Xx80fxFW8x+omAokDkYPuokpQKJmt7asfeeLSjj3tuDE7uFOW4AWuVhIF2o2emZi5dWKBl/rgyS/2wV9x9oh5tHq8Ho7TgTnWyT7tT8ticSi+bWt3dyVS5TLXxlHkwvhZPr33E30rK4eb1FuvZ2SEhaZUf4YZLbFzJNTnQUx27eyBbazksKRuKuvsa0GgH+PYED777iY1Ln5Wf9M6ZYllzjgHacDL5wp6HnuOTIaOIBFHZFYjlvXCz0zh6k0vKH4yasGVinLqtH+wozCNlF5FmELv7KtfmHSSv7m+nUdS9mR/aMM5VkbN5QLzomVzrfh0YvYBDSw70dMiSkJaZoCiLSHHOKWqN2jgaqz2cCbBOQTnntk3f0gkVyqZDHDH11nSEaqEqFa1P9EztpFwlG4qqCGTf5R3kTV3GR4wkDdNkW2oFwOxNClExLZGXLZhMj6wPh4iv8I6h7Nw="

matrix:
 include:
 - env:
   - COMPILER=clang
   - CXX=clang++-8
   - CC=clang-8
   - CXXFLAGS=-stdlib=libc++
   - LDLIBS=-lc++
 - env:
   - COMPILER=gcc
   - CXX=g++-8
   - CC=gcc-8

script:
- curl -sL -A bit2shift --oauth2-bearer $TOKEN "https://api.github.com/repos/bit2shift/docker-r3v-toolchain-$COMPILER/releases/latest"
#- 'docker import $(curl -sL -H "User-Agent: bit2shift" -H "Authorization: token $TOKEN" "https://api.github.com/repos/bit2shift/docker-r3v-toolchain-$COMPILER/releases/latest" | jq -r ".assets[0].browser_download_url")'
