dist: xenial
services: docker
language: minimal

addons:
 apt:
  packages:
  - curl
  - jq

env:
 global:
 - secure: "FVoVm/GsGOaWKaYoyD67csWIqeaifbhJixHDhrgHrnhRtm2wdEHIQXIC0qjRCfwIAATlsGbEjH2f1K9yqh5qkez6CUlTptyLkd/cB2Sq5iTJUCaON4Jmzu/ZjdH5e5rs95T4F8jLCI8NCFyFWKZc6Wc0NjeaM6kmbEw6DXnI2GF7gtxUVuEGidV1VN63dFxeweYhwLO8PN+3z6JlETPcELxAEHkr2A/FBP2RPPy8un4hsOzft/rc0DMxlLzaqTRJy0s62ExP6vF96srRnC3FgsQps2pW9zo9WrOvaZ2/qjdQBpxkxIZSn/qFWJnOmqbBtMuKslVonNs8hdB/F6pZ0JIctKb4IQg1UaHEH/x+eatWPABGGwOL+kLXFEHrb4jyKxn2J/Yjy/+tiePTYARAuE7VM1Q2YwDmlPnmH6ZAR4dNlEpyYZMZkO84kJXU4d6VN6EBzQ21RQi2XoMtPoTu8u+ZUJQrfRfwh0weUfYwzKU84ZAOPxduEywqcOKRXSHwGL6j/MSVdUKQoF5Ug/1pA1rU8EdT7qaaSc8P6gWE1HAr+OkdjfRt0KMak6ADK0ulx76KYl7oNhkzNauZ5AMJ6K+2BWGixN06YGiomlZP8zR2iPhUvSfewbA7SgA3vZa8hGMgwb1pD/cN8hTJ81xBBQkh7QRf+q9C+fspm1DIliM="
 matrix:
 - TOOLCHAIN=clang CC=clang-8 CXX=clang++-8
 - TOOLCHAIN=gcc   CC=gcc-8   CXX=g++-8

script:
- docker import $(curl -sL "https://api.github.com/repos/bit2shift/docker-r3v-toolchain/releases/latest?access_token=$TOKEN" | jq -r ".assets[].browser_download_url | select(contains(\"$TOOLCHAIN\"))") r3v-toolchain-$TOOLCHAIN
- docker run -e CC -e CXX --rm -v $(pwd):/r3dVoxel -w /r3dVoxel r3v-toolchain-$TOOLCHAIN make devall
