language: cpp
dist: xenial

dependencies: &deps
- xorg-dev
- libvulkan-dev

matrix:
 include:
 - compiler: clang
 - compiler: gcc-8
   env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
   addons:
    apt:
     sources: ubuntu-toolchain-r-test
     packages:
     - g++-8
     - *deps

before_install: eval "${MATRIX_EVAL}"
script: make
